export const JSON_DATA_FETCH_REQUEST = 'JSON_DATA_FETCH_REQUEST';
export const JSON_DATA_FETCH_SUCCESS = 'JSON_DATA_FETCH_SUCCESS';
export const JSON_DATA_FETCH_FAILED = 'JSON_DATA_FETCH_FAILED';


export const API_DATA_FETCH_REQUEST = 'API_DATA_FETCH_REQUEST';
export const API_DATA_FETCH_SUCCESS = 'API_DATA_FETCH_SUCCESS';
export const API_DATA_FETCH_FAILED = 'API_DATA_FETCH_FAILED';

export const SAMPLE_API_DATA_FETCH_REQUEST = 'SAMPLE_API_DATA_FETCH_REQUEST';
export const SAMPLE_API_DATA_FETCH_SUCCESS = 'SAMPLE_API_DATA_FETCH_SUCCESS';
export const SAMPLE_API_DATA_FETCH_FAILED = 'SAMPLE_API_DATA_FETCH_FAILED';
