export const CRYPTO_CURRENCY_FETCH_REQUEST = 'CRYPTO_CURRENCY_FETCH_REQUEST';
export const CRYPTO_CURRENCY_FETCH_SUCCESS = 'CRYPTO_CURRENCY_FETCH_SUCCESS';
export const CRYPTO_CURRENCY_FETCH_FAILED = 'CRYPTO_CURRENCY_FETCH_FAILED';



